const background = [{
    darkmode: {
        home: '<style>:root{--cor-fundo: #121212;--cor-texto: #e0e0e0;--cor-link: #4caf50;--cor-fundo-secundario: #333;--cor-fundo-hover: #4caf50;--cor-link-ativo: #1e1e1e;--cor-link-hover: rgb(44, 44, 44);--cor-secundario: #444;}</style>',
        page_initial: '<style>:root {--cor-fundo: #121212;--cor-texto: #e0e0e0;--cor-cabecalho: #1f1f1f;--cor-borda-cabecalho: #333;--cor-icon-user: #e0e0e0;--cor-borda-icon-user: #555;--cor-botao-principal: #27ae60;--cor-botao-principal-hover: #2ecc71;--cor-botao-principal-ativo: #1e7e4d;--cor-container-users: #222;--cor-scrollbar: #333;--cor-scrollbar-thumb: #27ae60;--cor-user-procura: #333;--cor-user-procura-hover: #444;}</style>',
        buscar_user: '<style>:root{--color-background: #121212;--color-text: #e0e0e0;--color-heading: #fff;--color-container: #1e1e1e;--color-shadow: rgba(0, 0, 0, 0.4);--color-shadow-hover: rgba(0, 0, 0, 0.6);--color-secondary-text: #dcdde1;--color-primary: #27ae60;--color-primary-hover: #fff;--color-remove: #e74c3c;--color-remove-hover: #c0392b;}</style>',
        config_user: '<style>:root{--color-background-dark: #121212;--color-text-light: #e0e0e0;--color-background-light: #47b64b;--color-border-dark: #444;--color-background-darkmode: #2c2c2c;--color-text-dark: #ddd;--color-blue: #007bff;--color-green: #28a745;--color-hover-light: #444;--color-hover-text: whitesmoke;}</style>',
        chat_with_user: '<style>:root{--color-background: #121212;--color-text: #e0e0e0;--color-header: #1f1f1f;--color-container: #2a2a2a;--color-border-top: #121212;--color-input-bg: #404552;--color-input-placeholder: #7f8fa6;--color-button-bg: #27ae60;--color-button-hover: #1e8449;--color-own-message: #27ae60;--color-other-message: #487eb0;--color-message-text: white;--color-icon-border: #e0e0e0;--box-shadow-light: rgba(0, 0, 0, 0.1);--box-shadow-medium: rgba(0, 0, 0, 0.2);}</style>',
        chat: '<style>:root {--color-background: #1e1e1e;--color-text: #f5f5f5;--color-header: #006400;--color-shadow-medium: rgba(0, 0, 0, 0.4);--color-shadow-light: rgba(0, 0, 0, 0.3);--color-shadow-strong: rgba(0, 0, 0, 0.5);--color-shadow-hover: rgba(0, 0, 0, 0.6);--color-border: #444;--color-input-bg: #333;--color-input-bg-focus: #444;--color-primary: #66aaff;--color-heading: #e1e1e1;--color-container-bg: #2a2a2a;--color-container-hover: #333;--color-container-scrollbar: #444;--color-container-thumb: #666;--color-container-friends: #2a2a2a;--color-friend-bg: #333;--color-friend-name: #ccc;--color-friend-name-hover: #66aaff;}</style>',
        jogos: {
            cidade_dorme: '<style>:root {--color-background: #2c2f33;--color-text: #ffffff;--color-container-bg: #23272a;--color-shadow: rgba(0, 0, 0, 0.3);--color-shadow-hover: rgba(0, 0, 0, 0.7);--color-border-icon: #7289da;--bg-color-hover: rgb(9, 183, 189);}</style>'
        }
    },
    lightmode: {
        home: '<style>:root{--cor-fundo: #fafafa;--cor-texto: #333333;--cor-link: #1a73e8;--cor-fundo-secundario: #f0f0f0;--cor-fundo-hover: #1cb0eb;--cor-link-ativo: #dfdfdf;--cor-link-hover: #0c66d1;--cor-secundario: #bdbdbd;}</style>',
        page_initial: '<style>:root{--cor-fundo: #fafafa;--cor-texto: #333;--cor-cabecalho: #fff;--cor-borda-cabecalho: #ccc;--cor-icon-user: #333;--cor-borda-icon-user: #ccc;--cor-botao-principal: #007bff;--cor-botao-principal-hover: #0056b3;--cor-botao-principal-ativo: #004085;--cor-container-users: #f9f9f9;--cor-scrollbar: #ccc;--cor-scrollbar-thumb: #007bff;--cor-user-procura: #f0f0f0;--cor-user-procura-hover: #ddd;}</style>',
        buscar_user: '<style>:root{--color-background: #fafafa;--color-text: #333;--color-heading: #000;--color-container: #fff;--color-shadow: rgba(0, 0, 0, 0.2);--color-shadow-hover: rgba(0, 0, 0, 0.4);--color-secondary-text: #666;--color-primary: #007bff;--color-primary-hover: #ffffff;--color-remove: #e74c3c;--color-remove-hover: #c0392b;}</style>',
        config_user: '<style>:root {--color-background-dark: #f5f5f5;--color-text-light: #121212;--color-background-light: rgb(9, 199, 212);--color-border-dark: #ccc;--color-background-darkmode: rgb(9, 150, 185);--color-text-dark: #f5f5f5;--color-blue: #0056b3;--color-green: #47b64b;--color-hover-light: #dcdcdc;--color-hover-text: #000000;}</style>',
        chat_with_user: '<style>:root{--color-background: #fafafa;--color-text: #333;--color-header: #f1f1f1;--color-container: #fff;--color-border-top: #ddd;--color-input-bg: #f5f5f5;--color-input-placeholder: #bbb;--color-button-bg: #28a745;--color-button-hover: #218838;--color-own-message: #28a745;--color-other-message: #007bff;--color-message-text: #fff;--color-icon-border: #333;--box-shadow-light: rgba(0, 0, 0, 0.1);--box-shadow-medium: rgba(0, 0, 0, 0.2);}</style>',
        chat: '<style>:root {--color-background: #f5f5f5;--color-text: #333;--color-header: #0078d7;--color-shadow-medium: rgba(0, 0, 0, 0.2);--color-shadow-light: rgba(0, 0, 0, 0.1);--color-shadow-strong: rgba(0, 0, 0, 0.3);--color-shadow-hover: rgba(0, 0, 0, 0.4);--color-border: #ccc;--color-input-bg: #fff;--color-input-bg-focus: #eef5ff;--color-primary: #005fb8;--color-heading: #111;--color-container-bg: #fff;--color-container-hover: #f0f8ff;--color-container-scrollbar: #f0f0f0;--color-container-thumb: #999;--color-container-friends: #ffffff;--color-friend-bg: #f9f9f9;--color-friend-name: #555;--color-friend-name-hover: #0078d7;}</style>',
        jogos: {
            cidade_dorme: '<style>:root{--color-background: #f4f4f4;--color-text: #333333;--color-container-bg: #e8e8e8;--color-shadow: rgba(0, 0, 0, 0.1);--color-shadow-hover: rgba(0, 0, 0, 0.2);--color-border-icon: #4a90e2;--bg-color-hover: ;}</style>'
        }
    }
}];

module.exports = background;